#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:/home/firas/Documents/webapp/gwt-2.7.0-snapshot/gwt-user.jar:/home/firas/Documents/webapp/gwt-2.7.0-snapshot/gwt-dev.jar" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src com.nutrinfomics.geneway.client.model.plan.FoodItemTypeConstants  ;

